//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTRANO
    {
        public string MaTraNo { get; set; }
        public string MaDonNhap { get; set; }
        public Nullable<double> SoTienTra { get; set; }
    
        public virtual DONHANGNHAP DONHANGNHAP { get; set; }
        public virtual SOTRANO SOTRANO { get; set; }
    }
}
