//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATHANG
    {
        public int IdChiTietDatHang { get; set; }
        public int IdDatHang { get; set; }
        public string MaSP { get; set; }
        public decimal DonGia { get; set; }
        public decimal SoLuong { get; set; }
        public decimal GiamGia { get; set; }
        public decimal TongCong { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual DATHANG DATHANG { get; set; }
    }
}
