//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANGNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANGNHAP()
        {
            this.CHITIETDONNHAPs = new HashSet<CHITIETDONNHAP>();
            this.CHITIETTRANOes = new HashSet<CHITIETTRANO>();
        }
    
        public string MaDonNhap { get; set; }
        public string MaNCC { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public string KieuThanhToan { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONNHAP> CHITIETDONNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTRANO> CHITIETTRANOes { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
