//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public int IdGiaoDich { get; set; }
        public string MaSP { get; set; }
        public decimal SoLuong { get; set; }
        public System.DateTime NgayGiaoDich { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
