//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanHangEntities : DbContext
    {
        public QLBanHangEntities()
            : base("name=QLBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDONBAN> CHITIETDONBANs { get; set; }
        public virtual DbSet<CHITIETDONNHAP> CHITIETDONNHAPs { get; set; }
        public virtual DbSet<CHITIETKM> CHITIETKMs { get; set; }
        public virtual DbSet<CHITIETTHUNO> CHITIETTHUNOes { get; set; }
        public virtual DbSet<CHITIETTRANO> CHITIETTRANOes { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DONBANHANG> DONBANHANGs { get; set; }
        public virtual DbSet<DONHANGNHAP> DONHANGNHAPs { get; set; }
        public virtual DbSet<HANGKHUYENMAI> HANGKHUYENMAIs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHOHANG> KHOHANGs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHOMHANG> NHOMHANGs { get; set; }
        public virtual DbSet<PHIEUBAOHANH> PHIEUBAOHANHs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<SOTHUNO> SOTHUNOes { get; set; }
        public virtual DbSet<SOTRANO> SOTRANOes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual DbSet<DATHANG> DATHANGs { get; set; }
        public virtual DbSet<GIAODICH> GIAODICHes { get; set; }
    }
}
