//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBAOHANH
    {
        public string MaPBH { get; set; }
        public string MaKH { get; set; }
        public string ТепРВН { get; set; }
        public string LyDoBH { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string ThoiGianBH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
