//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONBANs = new HashSet<CHITIETDONBAN>();
            this.CHITIETDONNHAPs = new HashSet<CHITIETDONNHAP>();
            this.CHITIETKMs = new HashSet<CHITIETKM>();
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.GIAODICHes = new HashSet<GIAODICH>();
        }
    
        public string MaSP { get; set; }
        public string MaNH { get; set; }
        public string MaKho { get; set; }
        public string TenSP { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string DungLuong { get; set; }
        public string KichThuoc { get; set; }
        public string NhaSX { get; set; }
        public string NuocSX { get; set; }
        public string GiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONBAN> CHITIETDONBANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONNHAP> CHITIETDONNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKM> CHITIETKMs { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual NHOMHANG NHOMHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAODICH> GIAODICHes { get; set; }
    }
}
